Refactors actors to 3rd party contexts
wasp-lang/wasp-bot pull request #10
Opened 2023-02-03 11:15 UTC by infomiho

Refactors the notion of "actor" to regular usage + 3rd party contexts. 

- New naming
- Better function to split regular usage and 3rd contexts
- Better folder organisation

2023-02-03 11:18 UTC, infomiho commented on src/analytics/cli.js
> +fetchEventsForReportGenerator().then((events) => {
Moved the CLI code to a dedicated `cli.js` file that calcs and outputs analytics locally.

2023-02-06 16:06 UTC, Martinsos requested changes
@infomiho I think this is great, and that you did a nice split! One thing that troubles me still is naming, I don't think 3rd party context works very well in practice, as a name.

See other comments, I explained why I think so, and suggested some other names. If you want we can additionally think about some names together and make sure to come up with something good, and then do the final renaming.

2023-02-06 16:06 UTC, Martinsos commented on src/analytics/analytics.js
> +  const userEventsByProject = groupEventsByProject(regularUsageEvents)
This is a bit weird: we say "regularUsageEvents", but then we say "userEvents". Now we are using the same name for two things, aren't we?
We should probably use just one name.
The problem though is that `regularUsage` is a bit confusing name I think, while also long. While `userEvents` is also not great, and is not something that also works with 3rd party context. Well maybe it does but doesn't feel like the best solution any more.

What if we went the `executionEnv` route? Then we could call this `localEvents` and `localEventsByProject`. That would be better I think. Person would need to know what "local" means, but we could establish that. At least it is shorter than "regularUsage", carries more info with it, and it is to name the opposite: "nonLocal".

2023-02-06 16:06 UTC, Martinsos commented on src/telemetryContext/utils.js
> +function splitEventsByRegularUsageAnd3rdPartyContext(events) {
Follow up: I read the rest of PR and now I actually think it makes sense to change the name, it just propagates too much and I think it causes naming issues in other places also.

2023-02-08 09:59 UTC, infomiho commented on src/telemetryContext/utils.js
> +function splitEventsByRegularUsageAnd3rdPartyContext(events) {
I think `execution env` as a name makes a lot of sense 👍

I've gone with `groupEventsByExecutionEnv` and returning of `{ localEvents, groupedNonLocalEvents }` return value since it made most sense with current usage.

2023-02-08 10:25 UTC, infomiho commented on src/analytics/analytics.js
> +  const userEventsByProject = groupEventsByProject(regularUsageEvents)
I've adjusted the naming to move away from `userEvents` and moved towards using `localEvents` and `nonLocalEvents` nomenclature. I think it works well 👍

2023-02-10 13:40 UTC, Martinsos approved these changes
Awesome @infomiho , that is it! Left two nitpicky comments and approved -> merge when you want! LGTM

2023-02-10 13:40 UTC, Martinsos commented on src/analytics/executionEnvs.js
> +// telemetry data to PostHog
```suggestion
// telemetry data to PostHog.
```

Yes it is nitpicking, BUT :D, it is actually also a piece of information! `.` tells us that sentence is done, that the rest of it wasn't deleted by accident or that author didn't fall asleep while writing it.

It can be ok to ommit `.` when writing a sentence that started with small letter, like in a bullet point, but if writing a normal sentence with first capital letter (we like these) then it is nice to also put `.` at the end!

2023-02-10 13:40 UTC, Martinsos commented on src/analytics/executionEnvs.js
> +// to do this separation, but we also do some analysis on the rest of events.
```suggestion
// Organize events by the execution env:
//   - non-local: e.g. Replit, Gitpod, Github Codepsaces, CI, ... .
//   - local: User running Wasp on their computer.
```

Warning: nitpicking ahead!

Main thing I wanted to add here is make the list less of a "it is exactly these non local envs" and more "could be some of these", in order to make comment more robust to adding or removing execution envs in the future.

I also removed the info about us caring more about local -> I don't think it is really important here. It makes sense to separate it even without us caring about one more or less, they are fundamentally different.

2023-02-11 19:43 UTC, merged