React to updated message of guest user
wasp-lang/wasp-bot pull request #8
Opened 2023-01-25 19:00 UTC by Fecony

Listen for `messageUpdated` event, if it was edited by guest user and is more than 20 chars then remove guest role

> Needs testing because locally my bot doesn't have permissions to manage roles and idk why I tried to give him everything 🥲

2023-01-25 19:01 UTC, Fecony commented on src/discord-bot.js
> +      oldMessage.content.length < 20
It may not be necessary because if old message was <20 chars, user still has guest role

2023-02-01 11:26 UTC, Martinsos requested changes
@Fecony thanks for this, it looks good!

Did you find a way to test this, I guess not, it is pretty tricky to do it? If not I can test it once we are done.

Ok, so basically we want to run the same check if new message arrives, or if old message was updated, and it happened in introductions channel, and user has GUEST role. That makes sense to me.

I think this is good but we should remove duplication. We want one piecce of logic to handle both situations. Should we make a function? Smth like `function ifGuestIntroductionMessageHandleIt (newMessage, oldMessage = undefined)`. And then we would just call it at those two places, and almost all of the logic would be in it?

2023-02-01 18:17 UTC, Fecony commented
@Martinsos 
> Did you find a way to test this, I guess not, it is pretty tricky to do it? If not I can test it once we are done.

I have test bot where I tried to launch node + bot in demo server and it works. BUT I cannot add it a permission to remove roles and it fails on that part of code for me

> I think this is good but we should remove duplication. We want one piecce of logic to handle both situations. Should we 

Removed code duplication for `message` and `messageUpdated` looks like it really is just a same handler function if you don't want to change message for update or something
And `oldMessage` is not used really...

2023-02-02 12:48 UTC, Martinsos commented on src/discord-bot.js
> +  if (msg.content.startsWith('!analytics') && msg.channel.id.toString() === REPORTS_CHANNEL_ID) {
I thought we would handle only introductions messages both on new message and upatedMessage, not that we will also handle !analytics bot commands.

The way you did it now, we allow people to update their analytics commands. Well, maybe that is ok at the end? I guess it is not a bit problem! Ok, let's leave it like this then, sounds good actually.

2023-02-02 12:48 UTC, Martinsos commented on src/discord-bot.js
> +        `\n👋 Great to have you here! Pls introduce yourself with a message that's at least 2️⃣0️⃣ characters long and I will give you full access to the server. \n❌ BTW editing your old message won't
Oh we have to update now this line since editing old messages works now!

2023-02-02 13:08 UTC, Fecony commented on src/discord-bot.js
> +        `\n👋 Great to have you here! Pls introduce yourself with a message that's at least 2️⃣0️⃣ characters long and I will give you full access to the server. \n❌ BTW editing your old message won't
@Martinsos Updated by removing the self-hatred message :boi:

2023-02-02 13:09 UTC, Fecony commented on src/discord-bot.js
> +  if (msg.content.startsWith('!analytics') && msg.channel.id.toString() === REPORTS_CHANNEL_ID) {
Then I will leave it as is?
It probably makes sense to leave it just in `on:message` but I don't think it changes something

2023-02-02 14:04 UTC, Martinsos commented
Looking good, thanks @Fecony , I am merging it!!!

2023-02-02 14:04 UTC, Martinsos approved these changes
LGTM!

2023-02-02 14:08 UTC, merged