Generalizes actors and adds codepaces
wasp-lang/wasp-bot pull request #9
Opened 2023-01-31 16:23 UTC by infomiho

After adding the "codespaces" actor support to couple of spaces, I've noticed a possiblity to generalize and add better extension support. Nothing major, most "smarts" are copy pasted from previous impl.

2023-02-01 17:21 UTC, Martinsos requested changes
Couple of small things to fix, but we are almost there! Nice refactor btw, I like it!

Did you manage to test this locally, by running it on real posthog data? If so, and once you do that again after we are done with PR completely, you should make sure it also gets pushed to `production` branch so it gets deployed.

2023-02-01 17:21 UTC, Martinsos commented on src/analytics.js
> +function getNumUniqueByActorInLastPeriod(periods, actors = nonUserActors) {
Unique what? Users I believe? Let's mention that in the name!

2023-02-01 17:21 UTC, Martinsos commented on src/analytics.js
> +function getNumTotalByActor(eventsByActor, actors = nonUserActors) {
```suggestion
function getNumTotalUniqueUsersByActor(eventsByActor, actors = nonUserActors) {
```

2023-02-01 17:21 UTC, Martinsos commented on src/analytics.js
> +const actors = {
We have this here, but we also have "actorNames" below. Does it make sense to have both? If those are names, what are these? I am not sure which is why I am asking, but I am wondering if this one should just be an array, or if we should drop this one and just use the second one ("actorNames") albeit maybe renamed (or not).

2023-02-01 17:21 UTC, Martinsos commented on src/analytics.js
> +
Am I correct that `report` here is not what we call "report" in the rest of the file? If so, let's maybe call it somehow differently, or at least let's be very precise in comments and describe what it is?

And yes we really need to move this file to Typescript, it has reached its limits as untyped language I think :D.

2023-02-01 17:21 UTC, Martinsos commented on src/analytics.js
> +  [actors.codespaces]: 'Github Codespaces',
```suggestion
  [actors.codespaces]: 'GH Codespaces',
```

2023-02-01 17:21 UTC, Martinsos commented on src/analytics.js
> +// - values: 1 / 2 / 3
```suggestion
// For actors A, B and C with values 1, 2 and 3 returns:
// { names: "A / B / C",
//   values: "1 / 2 / 3" }
```

2023-02-02 09:48 UTC, infomiho commented on src/analytics.js
> +function getNumTotalByActor(eventsByActor, actors = nonUserActors) {
I've gone with `getTotalUniqueUsersByActor`

2023-02-02 09:49 UTC, infomiho commented on src/analytics.js
> +const actors = {
They serve two different purposes: one is a key used to group the events, other is a output friendly name :)

2023-02-02 09:51 UTC, infomiho commented on src/analytics.js
> +
I've updated this function in this iteration. It will return a string that can be added in the report string.

2023-02-02 09:58 UTC, infomiho commented on src/analytics.js
> -function findUsersFirstActivity (eventsOfUser) {
Moved to `utils/user.js` since it's unused currently, but I didn't want to delete it.

2023-02-02 09:58 UTC, infomiho commented on src/analytics.js
> -// Expects data to be:
Moved to `charts.js`

2023-02-02 09:58 UTC, infomiho commented on src/analytics.js
> -// zip([[1,2],[3,4,5],[6,7]]) == [[1,3,6],[2,4,7]]
Moved to `utils/general.js` since it's unused, but I didn't want to delete it.

2023-02-02 10:00 UTC, infomiho commented
Tested out locally the `analytics.js` to be working, but I didn't test out the `bot.js` though. No logic changes were done to the bot part, so @Martinsos and I agreed to push the bad boy to prod and test it like that.

2023-02-02 10:01 UTC, infomiho commented on .eslintrc.json
> +{
The default eslint config.

2023-02-02 13:06 UTC, Martinsos commented on src/analytics.js
> +const actors = {
Ah yes that is they key used in `context`! Should we then name it `actorsToContextKey`? That makes it PITA in the rest of the code though right? Maybe then you could at least write in the comment that values in this dictionary are also used for context keys?
Ok, we discussed this additionaly and concluded that we will do:
```js
actors = {
  replit: { contextKey: "replit", prettyName: "Replit" },
  codespaces: { ... },
  ...
}
```

2023-02-02 13:07 UTC, Martinsos commented on src/analytics.js
> -// zip([[1,2],[3,4,5],[6,7]]) == [[1,3,6],[2,4,7]]
You can delete this one, I guess I used it and then didn't need it anymore!

2023-02-02 13:52 UTC, Martinsos requested changes

2023-02-02 13:52 UTC, Martinsos commented on README.md
> +Copy env.example to .env and fill it with your PostHog API key and Discord bot token. If you are only running `analytics.js` you can leave the Discord token empty.
```suggestion
Copy env.example to .env and fill it with your PostHog API key and Discord bot.
Both are needed to run bot locally, but only PostHog API key is needed to run just analytics locally.
```

2023-02-02 13:52 UTC, Martinsos commented on README.md
> +Run `npm run testAnalytics` to run analytics manually and get the report in the CLI.
I would move this right under instructions on how to run bot locally.

2023-02-02 13:52 UTC, Martinsos commented on README.md
>  Deployed instance of server is running on Heroku. Whatever you push to `production` branch automatically gets re-deployed to Heroku.
I would this under special header called ### Deploying

2023-02-02 13:52 UTC, Martinsos commented on package.json
> +    "testAnalytics": "node ./src/analytics.js"
```suggestion
    "analytics": "node ./src/analytics.js",
    "bot": "node ./src/bot.js"
```
You might be running analytics locally not just to test them but to actually see what they return, so I would just call it `analytics`.
Also, if we have command for analytics, we can add one for `bot`, to be consistent.
We can then also update README to use `npm run bot` instead of `node ./src/bot.js`.

2023-02-02 13:52 UTC, Martinsos commented on src/actors.js
> +
We discussed how to construct non user actors list. I said function that filters tham each time. But I was wrong, we can do it just once, here:

```js
const nonUserActors = {}
for ([actorId, actor] of Object.entries(actors)) {
  if (actor !== actors.user) {
    nonUserActors[actorId] = actor
  }
}
```

More functional:
```js
const nonUserActors = Object.fromEntries(Object.entries(actors).filter([, a] => a !== actors.user))
```

Maybe I wrote some pseudocode here not sure hehe but I think the idea is clear.

And that is it, it happens on module initialization, and we can use it, right?

2023-02-02 13:52 UTC, Martinsos commented on src/actors.js
> +function getActorsOutputFromCounts(counts, actors = nonUserActors) {
Not bad, but might be better: `prettyShowCountByActors`.

Why? It tells us that subject is countByActors -> ok, so that means keys are actors, values are count -> we don't know of what, but ok. It also tells us what is done with the subject -> it is transformed into string that is nice, pretty, can be printed, ... .

`getActorsOutputFromCounts` -> not bad, but it doesn't say what kind of output at all -> is it printable? Is it even string? What is it for? We don't know. Also, we can guess that count is connected to actors somehow, but we don't really know how, or is it even connected.

2023-02-02 13:52 UTC, Martinsos commented on src/analytics.js
> +function getUniqueUsersByActorInPeriod(periods, eventsByActor, actors = nonUserActors) {
Nit.: I would maybe rename this one to start with `calc` instead of `get` just to be similar to other functions here. I usually use `calc` when it is a bit more than just getting something.

2023-02-02 13:52 UTC, Martinsos commented on src/analytics.js
> +// Organize events by the actors / source: Replit, Gitpod, Github Codepsaces, CI, or the normal usage (actors.user).
One thing to be careful about here, once you will be doing changes: is the returned object here going to use ContextKey values for its keys, or will use keys in `actors` for its keys? So far it was using ContextKey values if I am correct, but I think we want it to use keys from `actors`.

2023-02-02 13:52 UTC, Martinsos commented on src/analytics.js
> +function getTotalUniqueUsersByActor(eventsByActor, actors = nonUserActors) {
`actors` here shadows global actors which is not great.

2023-02-02 13:52 UTC, Martinsos commented on src/analytics.js
> -function findUsersFirstActivity (eventsOfUser) {
If it is not used, you can delete it!

2023-02-02 13:52 UTC, Martinsos commented on src/discord-bot.js
> -  bot.on('ready', async (evt) => {
Idea: Maaaaybe we could do `_evt`, just so in the future if someobdy is coding here, they have an idea that there is this thing they can get something from? I guess it stands for event, terrible name. If you don't like the idea, ok drop it.

2023-02-02 14:14 UTC, infomiho commented on src/discord-bot.js
> -  bot.on('ready', async (evt) => {
I don't want to disable linter for this specific line. If somebody in the future will have the need for this argument, they'll know how to add it :)

2023-02-02 14:15 UTC, infomiho commented on src/actors.js
> +
`Object.values` did the trick and adding and `id` property helped with filtering.

2023-02-02 14:26 UTC, Martinsos commented on src/discord-bot.js
> -  bot.on('ready', async (evt) => {
Ok! I thought linter would be happy with `_event`.

2023-02-02 14:37 UTC, Martinsos commented on README.md
> +Both are needed to run bot locally, but only PostHog API key is needed to run just analytics locally.
```suggestion
Both are needed to run bot locally, but only PostHog API key is needed to run just analytics locally.

```

2023-02-02 14:37 UTC, Martinsos commented on package.json
> +    "startBot": "node ./src/bot.js"
Nit.: I would put startBot first, because it is "stronger" / "more default", while calcAnalytics is more specific.

2023-02-02 14:37 UTC, Martinsos commented on src/actors.js
> +    user: { id: "user", contextKey: "user", name: "User" },
Why do we need `id`? Can't we just say that key is `id`?

2023-02-02 14:37 UTC, Martinsos commented on src/actors.js
> +// - "contextKey" is used to identify the actor in the event context
```suggestion
// - "contextKey" is used to identify the actor from the Posthog event context field
```

2023-02-02 14:37 UTC, Martinsos commented on src/actors.js
> +);
Actors are object, nonUserActors is list of ids -> they are quite different, but name sounds like they are very similar.

I see this possibly causing confusion.

We can make sure they are the same by making nonUserActors be same in structure like actors, or we can call it nonUserActorIds. I somehow like the first one better, but am not against the later per se.

2023-02-02 14:58 UTC, infomiho commented on src/actors.js
> +);
We discussed this offline 👍

2023-02-02 15:25 UTC, merged